/**

 * RECOVERY PROMPT

 * Used when:

 * - AI returns empty / invalid output

 * - Model switches mid-build

 * - API key rotates

 * - Build resumes after pause

 */

export function buildRecoveryPrompt(params: {

  projectName: string;

  appGoal: string;

  techStack: string;

  folderTree: string;

  completedFiles: string[];

  remainingFiles: string[];

  lastSuccessfulFile?: string;

}) {

  const {

    projectName,

    appGoal,

    techStack,

    folderTree,

    completedFiles,

    remainingFiles,

    lastSuccessfulFile

  } = params;

  return `

YOU ARE CONTINUING A PAUSED PRODUCTION BUILD.

This project is being generated by an automated system (AuraEdit).

You do NOT have access to previous conversations.

You must rely ONLY on the information below.

------------------------------------

PROJECT OVERVIEW:

- Name: ${projectName}

- Goal: ${appGoal}

- Tech Stack: ${techStack}

------------------------------------

PROJECT FOLDER STRUCTURE:

${folderTree}

------------------------------------

FILES SUCCESSFULLY GENERATED:

${completedFiles.length ? completedFiles.join("\n") : "NONE"}

------------------------------------

FILES STILL PENDING:

${remainingFiles.length ? remainingFiles.join("\n") : "NONE"}

------------------------------------

LAST SUCCESSFUL FILE:

${lastSuccessfulFile || "NONE"}

------------------------------------

IMPORTANT RULES:

- DO NOT regenerate completed files

- DO NOT change architecture

- DO NOT invent features

- Generate ONLY the NEXT required file

- Follow the SAME strict output format used previously

------------------------------------

YOUR TASK:

Continue the build by generating the NEXT file in order.

START NOW.

`;

}